### ISSUE TITLE
Remove FGDC/CSDGM

### ISSUE THREAD

**Issue by andGarc** [SESYNC-ci/data-package-lesson#3]
Remove FGDC/CSDGM text from the metadata examples since these are no longer current.

**Comment by reblake** [comment]
Is there another metadata standard for geospatial, meterological and/or similar types of data that might be relevant to include here in addition to ISO 19115?  I'd like to have at least two standards per category.

**Comment by andGarc** [comment]
I will include the [COARDS Conventions](https://ferret.pmel.noaa.gov/Ferret/documentation/coards-netcdf-conventions) as a second example. 
Also, [here](https://rdamsc.bath.ac.uk) is a catalog that lists different standards which could be useful.
