### ISSUE TITLE
Creating Metadata Screenshot

### ISSUE THREAD

**Issue by andGarc** [SESYNC-ci/data-package-lesson#4]
Add a description for the screenshot under **Creating metadata**.

What is this screenshot of?
The link does not take you to what the screenshot is showing. Maybe add a quick description of the steps on how to get there?

**Comment by reblake** [comment]
which screenshot does this refer to?  KNB?  or Data Curator?  Both screenshots have descriptions in the bullet just above them, but feel free to add more description to the bullet.
